name: Generate SRS Files

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'
    - name: Build
      run: go build -v ./cmd/csv_to_srs
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: csv_to_srs
        path: ./csv_to_srs
        retention-days: 1


  generate_srs:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Download artifact
      uses: actions/download-artifact@v5
      with:
        name: csv_to_srs
    - name: Set execute permission on csv_to_srs
      run: chmod +x ./csv_to_srs
    - name: Generating SRS files
      run: ./csv_to_srs -input_dir ./csv -output_dir ./srs
    - name: Add, commit, and push
      uses: actions4git/add-commit-push@v1.0.0
      with:
        path: ./srs
